%%{init: {'theme': 'base', 'themeVariables': {'fontSize': '14px'}}}%%

stateDiagram-v2
    direction LR
    [*] --> {{STATUS_1}}: Created
    {{STATUS_1}} --> {{STATUS_2}}: {{TRANSITION_1_WHO}} ({{TRANSITION_1_DATE}})
    {{STATUS_2}} --> {{STATUS_3}}: {{TRANSITION_2_WHO}} ({{TRANSITION_2_DATE}})

    state {{STATUS_1}} {
        note: {{STATUS_1_NOTE}}
    }
    state {{STATUS_3}} {
        note: {{STATUS_3_NOTE}}
    }