"""
ProdOps Phase 2 — Script Generator (v2.2)
===========================================
Takes parsed ticket parameters + env_config and generates
complete, configured, copy-paste-ready shell scripts.

v2.2 Changes:
  - FIX: Pod name no longer doubles the "prodops" prefix
  - NEW: Pre-check step validates destination paths exist before copy
  - NEW: Ticket context comment shows source text for file list
  - NEW: Cross-reference step checks past tickets for pattern validation
  - NEW: Known BlueKC dev path pattern documented (bluekc-stg/ is intentional)

Built from real runbooks:
  S3 Copy:      https://abacusinsights.atlassian.net/wiki/spaces/ES/pages/5629607976
  FHIR Cleanup: https://abacusinsights.atlassian.net/wiki/spaces/ES/pages/5836767241
"""

import os
import yaml
import logging
from datetime import datetime, timezone

from phase2.parsers.ticket_parser import S3CopyParams, FHIRCleanupParams

logger = logging.getLogger(__name__)

_env_config: dict | None = None


def load_env_config(config_path: str | None = None) -> dict:
    """Load and cache env_config.yaml."""
    global _env_config
    if _env_config is not None:
        return _env_config
    if config_path is None:
        config_path = os.path.join(
            os.path.dirname(os.path.dirname(__file__)),
            "config", "env_config.yaml",
        )
    with open(config_path, "r") as f:
        _env_config = yaml.safe_load(f)
    return _env_config


def resolve_customer(customer_name: str, config: dict) -> dict | None:
    """Resolve customer name to infra details."""
    customers = config.get("customers", {})

    if customer_name in customers:
        return customers[customer_name]

    for key, val in customers.items():
        if key.lower() == customer_name.lower():
            return val

    aliases = config.get("customer_aliases", {})
    for alias, canonical in aliases.items():
        if alias.lower() == customer_name.lower():
            return customers.get(canonical)

    return None


# ============================================================================
# S3 Copy Script Generator
# ============================================================================

def generate_s3_copy_script(params: S3CopyParams, config: dict | None = None) -> str:
    """
    Generate a complete S3 copy/sync script.
    Uses ACTUAL S3 URIs from the ticket — does not construct bucket names.
    """
    if config is None:
        config = load_env_config()

    customer_cfg = resolve_customer(params.customer, config)
    bg = config.get("break_glass", {})
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    if not customer_cfg:
        return _error_block(
            params.ticket_key,
            f"Customer '{params.customer}' not found in env_config.yaml.\n"
            f"Add it under 'customers:' with aws_profile and eks_cluster.",
        )

    if not params.is_valid:
        return _missing_fields_block(params.ticket_key, params.missing_fields)

    aws_profile = customer_cfg["aws_profile"]
    eks_cluster = customer_cfg["eks_cluster"]
    region = customer_cfg.get("region", "us-east-1")
    bg_ns = bg.get("namespace", "break-glass")
    bg_sa = bg.get("service_account", "break-glass")
    bg_image = bg.get("image", "amazon/aws-cli:latest")

    # FIX: Pod name — extract just the number, no double prefix
    ticket_number = params.ticket_key.split("-")[-1]
    pod_name = f"prodops-{ticket_number}"

    lines = []

    # Header
    lines.append("#!/bin/bash")
    lines.append(f"# {'=' * 68}")
    lines.append(f"# {params.ticket_key}: {params.summary[:60]}")
    lines.append(f"# Generated by ProdOps Bot — {ts}")
    lines.append(f"# Customer: {params.customer}")
    lines.append(f"# Direction: {params.source_env} → {', '.join(params.dest_envs)}")
    lines.append(f"# ⚠️  REVIEW EVERY STEP BEFORE EXECUTING")
    lines.append(f"# {'=' * 68}")
    lines.append("")

    # NEW: Ticket context — show what the ticket actually says
    lines.append(f"# --- Ticket context (from {params.ticket_key} description) ---")
    if params.source_uris:
        lines.append(f"# Source: {params.source_uris[0]}")
    for i, dst in enumerate(params.dest_uris):
        lines.append(f"# Dest {i+1}: {dst}")
    if params.specific_files:
        lines.append(f"# Files listed in ticket ({len(params.specific_files)}):")
        for fname in params.specific_files[:15]:
            lines.append(f"#   • {fname}")
        if len(params.specific_files) > 15:
            lines.append(f"#   ... and {len(params.specific_files) - 15} more")
    lines.append(f"# ---")
    lines.append("")

    # Warnings
    for warn in params.warnings:
        lines.append(f"# {warn}")

    # NEW: Cross-reference known patterns
    known_patterns = config.get("known_path_patterns", {})
    customer_lower = params.customer.lower()
    if customer_lower in known_patterns:
        pattern_info = known_patterns[customer_lower]
        if pattern_info.get("dev_uses_stg_folder"):
            lines.append(f"# ℹ️  Known pattern: {params.customer} dev bucket uses "
                         f"'{pattern_info.get('dev_folder', 'stg')}' folder path (confirmed in "
                         f"{pattern_info.get('confirmed_tickets', 'past tickets')}). This is intentional.")

    if params.warnings or customer_lower in known_patterns:
        lines.append("")

    lines.append("set -euo pipefail")
    lines.append("")

    # Step 1: AWS SSO Login
    lines.append("# === STEP 1: AWS SSO Login ===")
    lines.append(f"aws sso login --profile {aws_profile}")
    lines.append("")

    # Step 2: Update kubeconfig
    lines.append("# === STEP 2: Update kubeconfig ===")
    lines.append(
        f"aws eks update-kubeconfig --region {region} "
        f"--name {eks_cluster} "
        f"--profile {aws_profile} "
        f"--alias {eks_cluster}"
    )
    lines.append("")

    # Step 3: Launch break-glass pod
    lines.append("# === STEP 3: Launch break-glass pod ===")
    lines.append(f"kubectl run --context {eks_cluster} \\")
    lines.append(f"  --namespace {bg_ns} -it --rm \\")
    lines.append(f"  --image {bg_image} \\")
    lines.append(f'  --overrides \'{{"spec": {{"serviceAccount": "{bg_sa}"}}}}\' \\')
    lines.append(f"  --restart=Never {pod_name} --command -- sh")
    lines.append("")
    lines.append(f"# {'=' * 68}")
    lines.append("# ⬇️  COMMANDS BELOW RUN INSIDE THE BREAK-GLASS POD ⬇️")
    lines.append(f"# {'=' * 68}")
    lines.append("")

    # Step 4: Verify identity
    lines.append("# === STEP 4 (inside pod): Verify AWS identity ===")
    lines.append("aws sts get-caller-identity")
    lines.append("")

    # NEW: Step 5 — Pre-check: validate paths exist
    lines.append("# === STEP 5 (inside pod): PRE-CHECK — verify paths exist ===")
    for i, src in enumerate(params.source_uris):
        lines.append(f'echo "--- Checking SOURCE [{i+1}] exists ---"')
        if params.specific_files:
            for fname in params.specific_files[:5]:
                lines.append(f"aws s3 ls {src.rstrip('/')}/{fname} || echo '❌ NOT FOUND: {fname}'")
        else:
            lines.append(f"aws s3 ls {src} --recursive --summarize | tail -n 2 || echo '❌ SOURCE PATH NOT FOUND'")
    for i, dst in enumerate(params.dest_uris):
        lines.append(f'echo "--- Checking DESTINATION [{i+1}] path is reachable ---"')
        lines.append(f"aws s3 ls {dst} 2>/dev/null && echo '✅ Dest path exists' || echo '⚠️ Dest path does not exist yet (will be created on copy)'")
    lines.append('echo "👆 Verify all source files exist before proceeding."')
    lines.append("")

    # Step 6: Baseline counts
    lines.append("# === STEP 6 (inside pod): Baseline counts BEFORE copy ===")
    for i, src in enumerate(params.source_uris):
        lines.append(f'echo "--- SOURCE [{i+1}] ---"')
        lines.append(f"aws s3 ls {src} --recursive --human-readable --summarize | tail -n 2")
    for i, dst in enumerate(params.dest_uris):
        lines.append(f'echo "--- DESTINATION [{i+1}] (before) ---"')
        lines.append(f"aws s3 ls {dst} --recursive --human-readable --summarize | tail -n 2")
    lines.append("")

    # Build copy pairs
    copy_pairs = _build_copy_pairs(params)

    # Step 7: Dry run
    lines.append("# === STEP 7 (inside pod): DRY RUN — MANDATORY ===")
    for src, dst in copy_pairs:
        if params.specific_files and len(params.specific_files) <= 10:
            for fname in params.specific_files:
                lines.append(f"aws s3 cp {src.rstrip('/')}/{fname} {dst.rstrip('/')}/{fname} --dryrun")
        else:
            lines.append(f"aws s3 {params.copy_method} {src} {dst} --dryrun | head -n 50")
            lines.append(f"aws s3 {params.copy_method} {src} {dst} --dryrun | wc -l")
    lines.append("")
    lines.append('echo "👆 Review dry-run output. Proceed only if paths and file names look correct."')
    lines.append("")

    # Step 8: Execute
    lines.append("# === STEP 8 (inside pod): EXECUTE — only after dry-run review ===")
    for src, dst in copy_pairs:
        if params.specific_files and len(params.specific_files) <= 10:
            for fname in params.specific_files:
                lines.append(f"aws s3 cp {src.rstrip('/')}/{fname} {dst.rstrip('/')}/{fname} --only-show-errors")
        else:
            lines.append(f"aws s3 {params.copy_method} {src} {dst} --only-show-errors")
    lines.append("")

    # Step 9: Post-validation
    lines.append("# === STEP 9 (inside pod): POST-VALIDATION ===")
    for src, dst in copy_pairs:
        if params.copy_method == "sync" and not params.specific_files:
            lines.append(f"# Verify no remaining diffs:")
            lines.append(f"aws s3 sync {src} {dst} --dryrun | head -n 20")
    if params.specific_files:
        lines.append("# Verify each file was copied:")
        for src, dst in copy_pairs:
            for fname in params.specific_files:
                lines.append(f"aws s3 ls {dst.rstrip('/')}/{fname} --human-readable || echo '❌ MISSING: {fname}'")
    else:
        for i, src in enumerate(params.source_uris):
            lines.append(f'echo "--- FINAL SOURCE [{i+1}] ---"')
            lines.append(f"aws s3 ls {src} --recursive --human-readable --summarize | tail -n 2")
        for i, dst in enumerate(params.dest_uris):
            lines.append(f'echo "--- FINAL DESTINATION [{i+1}] ---"')
            lines.append(f"aws s3 ls {dst} --recursive --human-readable --summarize | tail -n 2")
    lines.append("")

    # Step 10: Cleanup
    lines.append("# === STEP 10: Exit pod (auto-deletes with --rm) ===")
    lines.append("exit")

    return "\n".join(lines)


def _build_copy_pairs(params: S3CopyParams) -> list[tuple[str, str]]:
    """Build (source, dest) pairs for copy commands."""
    if len(params.source_uris) == 1:
        return [(params.source_uris[0], dst) for dst in params.dest_uris]
    elif len(params.source_uris) == len(params.dest_uris):
        return list(zip(params.source_uris, params.dest_uris))
    else:
        return [(params.source_uris[0], dst) for dst in params.dest_uris]


# ============================================================================
# FHIR Cleanup Script Generator
# ============================================================================

def generate_fhir_cleanup_script(params: FHIRCleanupParams, config: dict | None = None) -> str:
    """
    Generate FHIR cleanup script(s).
    For multi-env tickets, generates separate script blocks per environment.
    """
    if config is None:
        config = load_env_config()

    customer_cfg = resolve_customer(params.customer, config)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    if not customer_cfg:
        return _error_block(
            params.ticket_key,
            f"Customer '{params.customer}' not found in env_config.yaml.",
        )

    if not params.is_valid:
        return _missing_fields_block(params.ticket_key, params.missing_fields)

    aws_profile = customer_cfg["aws_profile"]

    # Build header with warnings
    header_lines = []
    for warn in params.warnings:
        header_lines.append(warn)
    header = "\n".join(header_lines) + "\n\n" if header_lines else ""

    # Generate a script block for each FHIR environment
    script_blocks = []
    for fhir_env in params.fhir_environments:
        block = _generate_single_fhir_block(
            params=params,
            fhir_env=fhir_env,
            aws_profile=aws_profile,
            ts=ts,
        )
        script_blocks.append(block)

    return header + "\n\n".join(script_blocks)


def _generate_single_fhir_block(
    params: FHIRCleanupParams,
    fhir_env: str,
    aws_profile: str,
    ts: str,
) -> str:
    """Generate script for a single FHIR environment."""

    is_prod = "prd" in fhir_env or "prod" in fhir_env
    catalog = params.get_catalog(fhir_env)
    env_tables = params.get_tables_for_env(fhir_env)

    # Build filter flags
    filter_flags = []
    for rt in params.resource_types:
        filter_flags.append(f"  -f {rt}")
    for profile in params.profile_urls:
        filter_flags.append(f'  -f "{profile}"')
    filter_str = " \\\n".join(filter_flags) if filter_flags else "  # ⚠️ No resource filters found — add -f flags manually"

    lines = []

    # Header
    if len(params.fhir_environments) > 1:
        lines.append(f"# ╔{'═' * 54}╗")
        lines.append(f"# ║  ENVIRONMENT: {fhir_env:<39}║")
        lines.append(f"# ╚{'═' * 54}╝")
        lines.append("")

    lines.append("#!/bin/bash")
    lines.append(f"# {'=' * 68}")
    lines.append(f"# {params.ticket_key}: {params.summary[:60]}")
    lines.append(f"# Generated by ProdOps Bot — {ts}")
    lines.append(f"# Customer: {params.customer} | Environment: {fhir_env}")
    if catalog:
        lines.append(f"# Databricks catalog: {catalog}")

    # NEW: Ticket context
    lines.append(f"# ---")
    lines.append(f"# Resources: {', '.join(params.resource_types) if params.resource_types else 'see profile URLs below'}")
    if params.metadata_tables:
        lines.append(f"# Metadata tables: {', '.join(t.split('.')[-1] for t in params.metadata_tables[:4])}")
    lines.append(f"# ---")

    if is_prod:
        lines.append(f"# ⚠️  PRODUCTION ENVIRONMENT — --force-prod required")
    lines.append(f"# ⚠️  REVIEW EVERY STEP BEFORE EXECUTING")
    lines.append(f"# {'=' * 68}")
    lines.append("")

    # Prerequisites
    lines.append("# === PREREQUISITES ===")
    lines.append("# ✅ JIT access activated for this tenant")
    lines.append("# ✅ fhir_cleanup.py + fhir_environments.yaml downloaded")
    lines.append("# ✅ Python venv with pyyaml>=6.0")
    lines.append("")

    # Step 1: AWS SSO Login
    lines.append("# === STEP 1: AWS SSO Login ===")
    lines.append(f"aws sso login --profile {aws_profile}")
    lines.append("")

    # Step 2: Dry run
    lines.append("# === STEP 2: DRY RUN — MANDATORY ===")
    lines.append(f"python fhir_cleanup.py \\")
    lines.append(f"  --config ./fhir_environments.yaml \\")
    lines.append(f"  -e {fhir_env} \\")
    lines.append(f"{filter_str} \\")
    lines.append(f"  --dry-run")
    lines.append("")

    # Step 3: Databricks metadata check
    if env_tables:
        lines.append("# === STEP 3: Verify counts in Databricks SQL ===")
        count_parts = []
        for t in env_tables:
            table_ref = t if "." in t and "_catalog" in t else f"{catalog}.{t}" if catalog else t
            short_name = t.split(".")[-1]
            count_parts.append(f"SELECT '{short_name}' AS tbl, COUNT(*) AS cnt FROM {table_ref}")
        count_query = "\nUNION ALL\n".join(count_parts)
        lines.append(f"# {count_query};")
        lines.append("")
    else:
        lines.append("# === STEP 3: (No metadata tables specified — skip) ===")
        lines.append("")

    # Step 4: Execute
    lines.append('echo "👆 Review dry-run counts. Proceed only if they match expectations."')
    lines.append("")
    lines.append("# === STEP 4: EXECUTE — only after dry-run verification ===")
    lines.append(f"python fhir_cleanup.py \\")
    lines.append(f"  --config ./fhir_environments.yaml \\")
    lines.append(f"  -e {fhir_env} \\")
    lines.append(f"{filter_str} \\")
    if is_prod:
        lines.append(f"  --execute --force-prod")
    else:
        lines.append(f"  --execute")
    lines.append("")

    # Step 5: Metadata cleanup
    if env_tables:
        lines.append("# === STEP 5: Databricks metadata cleanup (AFTER MongoDB delete confirmed) ===")
        for t in env_tables:
            table_ref = t if "." in t and "_catalog" in t else f"{catalog}.{t}" if catalog else t
            lines.append(f"# DELETE FROM {table_ref};")
        lines.append("")
        lines.append("# Verify 0 records after delete:")
        for t in env_tables:
            table_ref = t if "." in t and "_catalog" in t else f"{catalog}.{t}" if catalog else t
            lines.append(f"# SELECT COUNT(*) FROM {table_ref};")
        lines.append("")

    # FHIR server URLs
    if params.fhir_server_urls:
        lines.append("# === FHIR Server URLs (for manual verification) ===")
        for url in params.fhir_server_urls:
            lines.append(f"# {url}")
        lines.append("")

    # Troubleshooting
    lines.append("# === TROUBLESHOOTING ===")
    lines.append("# 'Environment not allowlisted' → Add to fhir_environments.yaml")
    lines.append("# 'AWS credentials not available' → Run aws sso login")
    lines.append("# 'No running MongoDB pods' → Check EKS context + namespace")
    if is_prod:
        lines.append("# 'Environment is marked prod' → Must use --force-prod")
    lines.append("# Count mismatch → STOP. Contact ticket reporter before deleting")

    return "\n".join(lines)


# ============================================================================
# Error / Missing Field Blocks
# ============================================================================

def _error_block(ticket_key: str, message: str) -> str:
    return (
        f"⚠️ *Script Generation Failed for {ticket_key}*\n\n"
        f"```\n{message}\n```\n\n"
        f"Check env_config.yaml and ensure the customer is configured."
    )


def _missing_fields_block(ticket_key: str, missing: list[str]) -> str:
    field_list = "\n".join(f"  • {f}" for f in missing)
    return (
        f"⚠️ *Cannot generate script for {ticket_key}* — missing required info:\n\n"
        f"{field_list}\n\n"
        f"Provide the missing details when requesting the script."
    )
